---
title: "Final"
author: "Felix Bridgeman & Liam Varela"
date: "2024-05-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(MASS)
library(biotools)
library(klaR)
library(car)
library(lubridate)
library(readxl)
library(ggExtra)
library(GGally)
library(plotly)
library(heplots)
library(nnet)
library(pROC)
library(corrplot)
library(aplpack)
library(fpc)
library(cluster)
library(ape)
library(vegan)
library(vegan3d)
library(mgcv)
library(rgl)
library(psych)
library(EFAtools)
library(knitr)
library(kableExtra)
library(dplyr)
library(pubtheme)
```

# Import Data

```{r}
dred <- read.csv("data/winequality-red.csv", sep = ";")
dwhite <- read.csv("data/winequality-white.csv" , sep = ";")
dnames <- read.csv("data/winequality.names", sep = "\t")
d <- rbind(dred, dwhite)

head(d)

# make ID column
d$ID <- 1:nrow(d)
# move ID column to front
d <- d[,c(ncol(d), 1:(ncol(d)-1))]

```

# Summaries of Data

```{r}
summary(d)
```
# Plots

```{r, fig.width=8, fig.height=10}
# plot histograms of all variables
dd <- d %>%
  pivot_longer(cols = -ID,
               names_to = "variable",
               values_to = "value")
g <- ggplot(dd,
            aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(~variable, scales = "free",
             nrow = 5)

g

```

## Comments:

- pH appears normally distributed
- sulphates, alcohol, and quality appear right-skewed


## Now let's standardize data

```{r, fig.width=8, fig.height=10}
dc <- d
dc[-1] <- scale(d[-1])

dd <- dc %>%
  pivot_longer(cols = -ID,
               names_to = "variable",
               values_to = "value")

g <- ggplot(dd,
            aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(~variable, scales = "free",
             nrow = 5)
g
```
















